model_name: maskrcnn
image_folder: NPY_MR
image_ext: npy
datadir: /srv/storage/talc@storage4.nancy/multispeech/corpus/speech_production/iadi #/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/vsouzaribeiro/datasets
state_dict_fpath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/vocal-tract-seg/results/29/best_model.pt
save_to: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/vocal-tract-seg/results/29
# exclusion_list_filepath: /home/vsouzaribeiro/workspace/vocal-tract-seg/config/leave_one_out/swallowing.json
mode: rgb
size: [136, 136]
batch_size: 16
sequences:
    "ArtSpeech_Vocal_Tract_Segmentation/1640":
        - S10
        - S14
        - S16
        - S24
classes:
    - arytenoid-cartilage
    - epiglottis
    - lower-lip
    - pharynx
    - soft-palate-midline
    - thyroid-cartilage
    - tongue
    - upper-lip
    - vocal-folds
